// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xizaujsaqeilwpaobgbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpemF1anNhcWVpbHdwYW9iZ2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzc0NDYsImV4cCI6MjA2MzY1MzQ0Nn0.Hdhz0liqNANmcK3RoVTauu4A-3Q5Mhb9C6onbAJdpuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);